import { Channel, PlaylistSource } from './types';

export const BUILT_IN_SOURCES: PlaylistSource[] = [
  {
    id: 'fancode',
    name: 'FanCode',
    type: 'built-in',
    channelCount: 11,
    loaded: true,
    active: true,
  },
  {
    id: 'akash',
    name: 'Akash',
    type: 'built-in',
    channelCount: 5,
    loaded: false,
    active: false,
  },
  {
    id: 'tapmad',
    name: 'Tapmad',
    type: 'built-in',
    channelCount: 4,
    loaded: false,
    active: false,
  },
  {
    id: 'fifalive',
    name: 'Fifa Live',
    type: 'built-in',
    channelCount: 3,
    loaded: false,
    active: false,
  },
  {
    id: 'sonyliv',
    name: 'SonyLiv',
    type: 'built-in',
    channelCount: 4,
    loaded: false,
    active: false,
  },
  {
    id: 'axsport',
    name: 'Axsport',
    type: 'built-in',
    channelCount: 3,
    loaded: false,
    active: false,
  },
  {
    id: 'roarzone',
    name: 'RoarZone',
    type: 'built-in',
    channelCount: 2,
    loaded: false,
    active: false,
  },
];

export const INITIAL_CHANNELS: Channel[] = [
  // ==================== FANCODE ====================
  {
    id: 'fc-1',
    name: "Guernsey Vs Jersey | ICC Men's T20 World Cup Qualifier Group B",
    logo: '🇬🇬 🆚 🇯🇪',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    category: 'Cricket',
    sourceId: 'fancode',
    online: true,
    resolution: '1920x1080',
    country: 'UK',
  },
  {
    id: 'fc-2',
    name: 'Croatia Vs Austria | ICC Men\'s T20 World Cup Europe Qualifier',
    logo: '🇭🇷 🆚 🇦🇹',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    category: 'Cricket',
    sourceId: 'fancode',
    online: true,
    resolution: '1920x1080',
    country: 'Europe',
  },
  {
    id: 'fc-3',
    name: 'Kenya Vs Mali | ICC Men\'s T20 World Cup Africa Qualifier',
    logo: '🇰🇪 🆚 🇲🇱',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    category: 'Cricket',
    sourceId: 'fancode',
    online: true,
    resolution: '1920x1080',
    country: 'Africa',
  },
  {
    id: 'fc-4',
    name: 'Botswana Vs Sierra Leone | ICC Men\'s T20 Africa Qualifier',
    logo: '🇧🇼 🆚 🇸🇱',
    url: 'https://test-streams.mux.dev/x36xhg/main.m3u8', // Real HLS
    category: 'Cricket',
    sourceId: 'fancode',
    online: true,
    resolution: '1280x720',
    country: 'Africa',
  },
  {
    id: 'fc-5',
    name: 'Hull City Vs Middlesbrough | EFL Championship Live Match',
    logo: '⚽ 🐯 🆚 🔴',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    category: 'Football',
    sourceId: 'fancode',
    online: true,
    resolution: '1920x1080',
    country: 'UK',
  },
  {
    id: 'fc-6',
    name: 'Charlton Athletic F.c Vs Portsmouth F.c',
    logo: '⚽ 🔴 🆚 🔵',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    category: 'Football',
    sourceId: 'fancode',
    online: true,
    resolution: '1920x1080',
    country: 'UK',
  },
  {
    id: 'fc-7',
    name: 'Celtic Vs Dunfermline Athletic | Scottish Cup',
    logo: '🍀 🆚 🏁',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4',
    category: 'Football',
    sourceId: 'fancode',
    online: true,
    resolution: '1920x1080',
    country: 'Scotland',
  },
  {
    id: 'fc-8',
    name: 'Center Court | ATP 250 Geneva Open',
    logo: '🎾 🇨🇭',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    category: 'Tennis',
    sourceId: 'fancode',
    online: true,
    resolution: '1920x1080',
    country: 'Switzerland',
  },
  {
    id: 'fc-9',
    name: 'Ignacio Buse Vs Tomas Barrios Vera | ATP Challenger',
    logo: '🎾 🇵🇪 🆚 🇨🇱',
    url: 'https://demo.unified-streaming.com/k8s/features/stable/video/tears-of-steel/tears-of-steel.ism/.m3u8', // Real HLS
    category: 'Tennis',
    sourceId: 'fancode',
    online: true,
    resolution: '1280x720',
    country: 'Peru',
  },
  {
    id: 'fc-10',
    name: 'Adac Gt Race 1 Zandvoort | ADAC GT Masters Live',
    logo: '🏎️ 🇳🇱',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4',
    category: 'Motorsports',
    sourceId: 'fancode',
    online: true,
    resolution: '1920x1080',
    country: 'Netherlands',
  },
  {
    id: 'fc-11',
    name: 'Day 3 Main Feed | The Senior Open Championship Presented by Rolex',
    logo: '⛳ 🏌️‍♂️',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4',
    category: 'Golf',
    sourceId: 'fancode',
    online: true,
    resolution: '1920x1080',
    country: 'UK',
  },

  // ==================== AKASH ====================
  {
    id: 'akash-1',
    name: 'Somoy TV (Live News Feed)',
    logo: '🔴 SOMOY',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    category: 'News',
    sourceId: 'akash',
    online: true,
    resolution: '1920x1080',
    country: 'Bangladesh',
  },
  {
    id: 'akash-2',
    name: 'Jamuna TV HD',
    logo: '📺 JAMUNA',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    category: 'News',
    sourceId: 'akash',
    online: true,
    resolution: '1920x1080',
    country: 'Bangladesh',
  },
  {
    id: 'akash-3',
    name: 'DBC News HD',
    logo: '📰 DBC',
    url: 'https://test-streams.mux.dev/x36xhg/main.m3u8', // Real HLS
    category: 'News',
    sourceId: 'akash',
    online: true,
    resolution: '1280x720',
    country: 'Bangladesh',
  },
  {
    id: 'akash-4',
    name: 'Maasranga TV Entertainment',
    logo: '🐟 MAAS',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    category: 'Entertainment',
    sourceId: 'akash',
    online: true,
    resolution: '1920x1080',
    country: 'Bangladesh',
  },
  {
    id: 'akash-5',
    name: 'Ekattor HD',
    logo: '🟢 71 News',
    url: 'https://demo.unified-streaming.com/k8s/features/stable/video/tears-of-steel/tears-of-steel.ism/.m3u8',
    category: 'News',
    sourceId: 'akash',
    online: true,
    resolution: '1280x720',
    country: 'Bangladesh',
  },

  // ==================== TAPMAD ====================
  {
    id: 'tap-1',
    name: 'IPL Live High-Velocity Stream',
    logo: '🏏 IPL Live',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4',
    category: 'Cricket',
    sourceId: 'tapmad',
    online: true,
    resolution: '1920x1080',
    country: 'India',
  },
  {
    id: 'tap-2',
    name: 'Pakistan vs England Test Match Feed 1',
    logo: '🇵🇰 🆚 🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    category: 'Cricket',
    sourceId: 'tapmad',
    online: true,
    resolution: '1920x1080',
    country: 'Pakistan',
  },
  {
    id: 'tap-3',
    name: 'PSL Islamabad United vs Lahore Qalandars',
    logo: '🏏 PSL Live',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    category: 'Cricket',
    sourceId: 'tapmad',
    online: true,
    resolution: '1920x1080',
    country: 'Pakistan',
  },
  {
    id: 'tap-4',
    name: 'CPL Guyana Amazon Warriors vs Trinbago Knight Riders',
    logo: '🌴 CPL Live',
    url: 'https://test-streams.mux.dev/x36xhg/main.m3u8',
    category: 'Cricket',
    sourceId: 'tapmad',
    online: true,
    resolution: '1280x720',
    country: 'Caribbean',
  },

  // ==================== FIFA LIVE ====================
  {
    id: 'fifa-1',
    name: 'FIFA World Cup Classic Match Highlights Channel',
    logo: '🏆 FIFA TV',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    category: 'Football',
    sourceId: 'fifalive',
    online: true,
    resolution: '1920x1080',
    country: 'International',
  },
  {
    id: 'fifa-2',
    name: 'Argentina Vs France Ultimate Finals replay',
    logo: '🇦🇷 🆚 🇫🇷',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    category: 'Football',
    sourceId: 'fifalive',
    online: true,
    resolution: '1920x1080',
    country: 'Qatar',
  },
  {
    id: 'fifa-3',
    name: 'Real Madrid vs FC Barcelona El Clasico Legends',
    logo: '⚪ 🆚 🔵🔴',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4',
    category: 'Football',
    sourceId: 'fifalive',
    online: true,
    resolution: '1920x1080',
    country: 'Spain',
  },

  // ==================== SONYLIV ====================
  {
    id: 'sony-1',
    name: 'Sony Ten 1 HD Live Feed',
    logo: '🔴 SONY TEN 1',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    category: 'Cricket',
    sourceId: 'sonyliv',
    online: true,
    resolution: '1920x1080',
    country: 'India',
  },
  {
    id: 'sony-2',
    name: 'Sony Ten 2 Football Live (Bundesliga, FA Cup)',
    logo: '⚽ SONY TEN 2',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    category: 'Football',
    sourceId: 'sonyliv',
    online: true,
    resolution: '1920x1080',
    country: 'Germany',
  },
  {
    id: 'sony-3',
    name: 'Sony Six T20 Action Channel',
    logo: '🏏 SONY SIX',
    url: 'https://test-streams.mux.dev/x36xhg/main.m3u8',
    category: 'Cricket',
    sourceId: 'sonyliv',
    online: true,
    resolution: '1280x720',
    country: 'India',
  },
  {
    id: 'sony-4',
    name: 'The Memorial Tournament - PGA Tour Segment',
    logo: '⛳ SONY GOLF',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    category: 'Golf',
    sourceId: 'sonyliv',
    online: true,
    resolution: '1920x1080',
    country: 'USA',
  },

  // ==================== AXSPORT ====================
  {
    id: 'ax-1',
    name: 'Roland Garros Center Court Match Feed',
    logo: '🎾 AX ROLAND',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    category: 'Tennis',
    sourceId: 'axsport',
    online: true,
    resolution: '1920x1080',
    country: 'France',
  },
  {
    id: 'ax-2',
    name: 'Wimbledon Live Court 1 Session Stream',
    logo: '🎾 AX WIMBLEDON',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    category: 'Tennis',
    sourceId: 'axsport',
    online: true,
    resolution: '1920x1080',
    country: 'UK',
  },
  {
    id: 'ax-3',
    name: 'US Open Flushing Meadows Men Arthur Ashe Court',
    logo: '🎾 AX US OPEN',
    url: 'https://test-streams.mux.dev/x36xhg/main.m3u8',
    category: 'Tennis',
    sourceId: 'axsport',
    online: true,
    resolution: '1280x720',
    country: 'USA',
  },

  // ==================== ROARZONE ====================
  {
    id: 'roar-1',
    name: 'Extreme Superbike Zandvoort Race Live',
    logo: '🏍️ ROAR MOTO',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4',
    category: 'Motorsports',
    sourceId: 'roarzone',
    online: true,
    resolution: '1920x1080',
    country: 'Netherlands',
  },
  {
    id: 'roar-2',
    name: 'Formula Race Legends Historical Highlights',
    logo: '🏁 ROAR Formula',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    category: 'Motorsports',
    sourceId: 'roarzone',
    online: true,
    resolution: '1920x1080',
    country: 'Monaco',
  },
];
